# Result analysis

This notebook loads one or more evaluation JSON files and builds a paper-style benchmark table. Edit `result_files` to add more models.

## Paper-style Columns

`MoE Method`, `PPL ↓`, `LAMBADA`, `BLiMP`, `CBT`, `HellaSwag`, `PIQA`, `ARC-Easy`, `RACE`, `SIQA`, `CommonSenseQA`, `AVG Acc ↑`, `AVG Rank ↓`

In [2]:
from pathlib import Path
import json
from html import escape
from zipfile import ZIP_DEFLATED, ZipFile

import pandas as pd
from IPython.display import HTML

pd.set_option("display.max_rows", 120)
pd.set_option("display.max_colwidth", 120)

# Add as many result files as you want here.
# Example: {"smoe": "path/to/smoe.json", "xmoe": "path/to/xmoe.json"}
result_files = {
    "Model-1000": "result-model-1000.pth.json",
}

notebook_dir = Path("/mnt/d/workspace/LibMoE/language_modeling/assets")
repo_root = notebook_dir.parents[1]

def resolve_result_path(path):
    path = Path(path).expanduser()
    candidates = [path, Path.cwd() / path, notebook_dir / path, repo_root / path]
    for candidate in candidates:
        if candidate.exists():
            return candidate.resolve()
    raise FileNotFoundError(f"Could not find result file: {path}")

loaded_results = {}
resolved_result_paths = {}
for model_name, path in result_files.items():
    result_path = resolve_result_path(path)
    with result_path.open("r", encoding="utf-8") as f:
        loaded_results[model_name] = json.load(f)
    resolved_result_paths[model_name] = result_path
    print(f"Loaded {model_name}: {len(loaded_results[model_name])} metrics from {result_path}")

default_model_name = next(iter(loaded_results))
results = loaded_results[default_model_name]
result_path = resolved_result_paths[default_model_name]

Loaded Model-1000: 110 metrics from /mnt/d/workspace/LibMoE/language_modeling/assets/result-model-1000.pth.json

## All Metrics

In [3]:
metrics = pd.DataFrame(
    [
        {
            "model": model_name,
            "metric": key,
            "group": key.split("/")[0],
            "name": "/".join(key.split("/")[1:]) if "/" in key else key,
            "value": value,
        }
        for model_name, model_results in loaded_results.items()
        for key, value in model_results.items()
    ]
).sort_values(["model", "group", "metric"]).reset_index(drop=True)

display(metrics)
metrics.to_csv("result-all-metrics.csv", index=False)

,model,metric,group,name,value
0,Model-1000,ai2arc/accuracy/ARC-Challenge,ai2arc,accuracy/ARC-Challenge,0.197425
1,Model-1000,ai2arc/accuracy/ARC-Easy,ai2arc,accuracy/ARC-Easy,0.260888
2,Model-1000,ai2arc/accuracy/group_average,ai2arc,accuracy/group_average,0.229156
3,Model-1000,ai2arc/accuracy/seq_average,ai2arc,accuracy/seq_average,0.239943
4,Model-1000,blimp/accuracy/adjunct_island,blimp,accuracy/adjunct_island,0.718000
5,Model-1000,blimp/accuracy/anaphor_gender_agreement,blimp,accuracy/anaphor_gender_agreement,0.441000
6,Model-1000,blimp/accuracy/anaphor_number_agreement,blimp,accuracy/anaphor_number_agreement,0.692000
7,Model-1000,blimp/accuracy/animate_subject_passive,blimp,accuracy/animate_subject_passive,0.663000
8,Model-1000,blimp/accuracy/animate_subject_trans,blimp,accuracy/animate_subject_trans,0.692000
9,Model-1000,blimp/accuracy/causative,blimp,accuracy/causative,0.494000
10,Model-1000,blimp/accuracy/complex_NP_island,blimp,accuracy/complex_NP_island,0.476000
11,Model-1000,blimp/accuracy/coordinate_structure_constraint_complex_left_branch,blimp,accuracy/coordinate_structure_constraint_complex_left_branch,0.249000
12,Model-1000,blimp/accuracy/coordinate_structure_constraint_object_extraction,blimp,accuracy/coordinate_structure_constraint_object_extraction,0.629000
13,Model-1000,blimp/accuracy/determiner_noun_agreement_1,blimp,accuracy/determiner_noun_agreement_1,0.811000
14,Model-1000,blimp/accuracy/determiner_noun_agreement_2,blimp,accuracy/determiner_noun_agreement_2,0.784000
15,Model-1000,blimp/accuracy/determiner_noun_agreement_irregular_1,blimp,accuracy/determiner_noun_agreement_irregular_1,0.605000
16,Model-1000,blimp/accuracy/determiner_noun_agreement_irregular_2,blimp,accuracy/determiner_noun_agreement_irregular_2,0.725000
17,Model-1000,blimp/accuracy/determiner_noun_agreement_with_adj_2,blimp,accuracy/determiner_noun_agreement_with_adj_2,0.712000
18,Model-1000,blimp/accuracy/determiner_noun_agreement_with_adj_irregular_1,blimp,accuracy/determiner_noun_agreement_with_adj_irregular_1,0.627000
19,Model-1000,blimp/accuracy/determiner_noun_agreement_with_adj_irregular_2,blimp,accuracy/determiner_noun_agreement_with_adj_irregular_2,0.669000
20,Model-1000,blimp/accuracy/determiner_noun_agreement_with_adjective_1,blimp,accuracy/determiner_noun_agreement_with_adjective_1,0.718000
21,Model-1000,blimp/accuracy/distractor_agreement_relational_noun,blimp,accuracy/distractor_agreement_relational_noun,0.327000
22,Model-1000,blimp/accuracy/distractor_agreement_relative_clause,blimp,accuracy/distractor_agreement_relative_clause,0.270000
23,Model-1000,blimp/accuracy/drop_argument,blimp,accuracy/drop_argument,0.738000
24,Model-1000,blimp/accuracy/ellipsis_n_bar_1,blimp,accuracy/ellipsis_n_bar_1,0.418000
25,Model-1000,blimp/accuracy/ellipsis_n_bar_2,blimp,accuracy/ellipsis_n_bar_2,0.497000
26,Model-1000,blimp/accuracy/existential_there_object_raising,blimp,accuracy/existential_there_object_raising,0.715000
27,Model-1000,blimp/accuracy/existential_there_quantifiers_1,blimp,accuracy/existential_there_quantifiers_1,0.856000
28,Model-1000,blimp/accuracy/existential_there_quantifiers_2,blimp,accuracy/existential_there_quantifiers_2,0.157000
29,Model-1000,blimp/accuracy/existential_there_subject_raising,blimp,accuracy/existential_there_subject_raising,0.632000
30,Model-1000,blimp/accuracy/expletive_it_object_raising,blimp,accuracy/expletive_it_object_raising,0.713000
31,Model-1000,blimp/accuracy/group_average,blimp,accuracy/group_average,0.589866
32,Model-1000,blimp/accuracy/inchoative,blimp,accuracy/inchoative,0.350000
33,Model-1000,blimp/accuracy/intransitive,blimp,accuracy/intransitive,0.538000
34,Model-1000,blimp/accuracy/irregular_past_participle_adjectives,blimp,accuracy/irregular_past_participle_adjectives,0.619000
35,Model-1000,blimp/accuracy/irregular_past_participle_verbs,blimp,accuracy/irregular_past_participle_verbs,0.598000
36,Model-1000,blimp/accuracy/irregular_plural_subject_verb_agreement_1,blimp,accuracy/irregular_plural_subject_verb_agreement_1,0.592000
37,Model-1000,blimp/accuracy/irregular_plural_subject_verb_agreement_2,blimp,accuracy/irregular_plural_subject_verb_agreement_2,0.678000
38,Model-1000,blimp/accuracy/left_branch_island_echo_question,blimp,accuracy/left_branch_island_echo_question,0.588000
39,Model-1000,blimp/accuracy/left_branch_island_simple_question,blimp,accuracy/left_branch_island_simple_question,0.313000
40,Model-1000,blimp/accuracy/matrix_question_npi_licensor_present,blimp,accuracy/matrix_question_npi_licensor_present,0.049000
41,Model-1000,blimp/accuracy/npi_present_1,blimp,accuracy/npi_present_1,0.289000
42,Model-1000,blimp/accuracy/npi_present_2,blimp,accuracy/npi_present_2,0.375000
43,Model-1000,blimp/accuracy/only_npi_licensor_present,blimp,accuracy/only_npi_licensor_present,0.449000
44,Model-1000,blimp/accuracy/only_npi_scope,blimp,accuracy/only_npi_scope,0.638000
45,Model-1000,blimp/accuracy/passive_1,blimp,accuracy/passive_1,0.681000
46,Model-1000,blimp/accuracy/passive_2,blimp,accuracy/passive_2,0.674000
47,Model-1000,blimp/accuracy/principle_A_c_command,blimp,accuracy/principle_A_c_command,0.566000
48,Model-1000,blimp/accuracy/principle_A_case_1,blimp,accuracy/principle_A_case_1,1.000000
49,Model-1000,blimp/accuracy/principle_A_case_2,blimp,accuracy/principle_A_case_2,0.699000
50,Model-1000,blimp/accuracy/principle_A_domain_1,blimp,accuracy/principle_A_domain_1,0.936000
51,Model-1000,blimp/accuracy/principle_A_domain_2,blimp,accuracy/principle_A_domain_2,0.600000
52,Model-1000,blimp/accuracy/principle_A_domain_3,blimp,accuracy/principle_A_domain_3,0.472000
53,Model-1000,blimp/accuracy/principle_A_reconstruction,blimp,accuracy/principle_A_reconstruction,0.432000
54,Model-1000,blimp/accuracy/regular_plural_subject_verb_agreement_1,blimp,accuracy/regular_plural_subject_verb_agreement_1,0.653000
55,Model-1000,blimp/accuracy/regular_plural_subject_verb_agreement_2,blimp,accuracy/regular_plural_subject_verb_agreement_2,0.638000
56,Model-1000,blimp/accuracy/sentential_negation_npi_licensor_present,blimp,accuracy/sentential_negation_npi_licensor_present,0.979000
57,Model-1000,blimp/accuracy/sentential_negation_npi_scope,blimp,accuracy/sentential_negation_npi_scope,0.391000
58,Model-1000,blimp/accuracy/sentential_subject_island,blimp,accuracy/sentential_subject_island,0.305000
59,Model-1000,blimp/accuracy/seq_average,blimp,accuracy/seq_average,0.589866
60,Model-1000,blimp/accuracy/superlative_quantifiers_1,blimp,accuracy/superlative_quantifiers_1,0.657000
61,Model-1000,blimp/accuracy/superlative_quantifiers_2,blimp,accuracy/superlative_quantifiers_2,0.721000
62,Model-1000,blimp/accuracy/tough_vs_raising_1,blimp,accuracy/tough_vs_raising_1,0.420000
63,Model-1000,blimp/accuracy/tough_vs_raising_2,blimp,accuracy/tough_vs_raising_2,0.643000
64,Model-1000,blimp/accuracy/transitive,blimp,accuracy/transitive,0.667000
65,Model-1000,blimp/accuracy/wh_island,blimp,accuracy/wh_island,0.660000
66,Model-1000,blimp/accuracy/wh_questions_object_gap,blimp,accuracy/wh_questions_object_gap,0.716000
67,Model-1000,blimp/accuracy/wh_questions_subject_gap,blimp,accuracy/wh_questions_subject_gap,0.908000
68,Model-1000,blimp/accuracy/wh_questions_subject_gap_long_distance,blimp,accuracy/wh_questions_subject_gap_long_distance,0.979000
69,Model-1000,blimp/accuracy/wh_vs_that_no_gap,blimp,accuracy/wh_vs_that_no_gap,0.989000
70,Model-1000,blimp/accuracy/wh_vs_that_no_gap_long_distance,blimp,accuracy/wh_vs_that_no_gap_long_distance,0.997000
71,Model-1000,blimp/accuracy/wh_vs_that_with_gap,blimp,accuracy/wh_vs_that_with_gap,0.029000
72,Model-1000,blimp/accuracy/wh_vs_that_with_gap_long_distance,blimp,accuracy/wh_vs_that_with_gap_long_distance,0.005000
73,Model-1000,cbt/accuracy/CN,cbt,accuracy/CN,0.312400
74,Model-1000,cbt/accuracy/NE,cbt,accuracy/NE,0.159455
75,Model-1000,cbt/accuracy/P,cbt,accuracy/P,0.668400
76,Model-1000,cbt/accuracy/V,cbt,accuracy/V,0.638400
77,Model-1000,cbt/accuracy/group_average,cbt,accuracy/group_average,0.444664
78,Model-1000,cbt/accuracy/seq_average,cbt,accuracy/seq_average,0.444778
79,Model-1000,commonsenseqa/accuracy/dev_rand_split,commonsenseqa,accuracy/dev_rand_split,0.208845
80,Model-1000,commonsenseqa/accuracy/group_average,commonsenseqa,accuracy/group_average,0.208845
81,Model-1000,commonsenseqa/accuracy/seq_average,commonsenseqa,accuracy/seq_average,0.208845
82,Model-1000,hellaswag/accuracy/group_average,hellaswag,accuracy/group_average,0.245071
83,Model-1000,hellaswag/accuracy/seq_average,hellaswag,accuracy/seq_average,0.245071
84,Model-1000,hellaswag/accuracy/val,hellaswag,accuracy/val,0.245071
85,Model-1000,lambada/accuracy/openai_last_token,lambada,accuracy/openai_last_token,0.285326
86,Model-1000,lambada/accuracy/total,lambada,accuracy/total,0.002135
87,Model-1000,lambada/lm_loss,lambada,lm_loss,4.635684
88,Model-1000,lambada/lm_perplexity,lambada,lm_perplexity,103.098418
89,Model-1000,lambada/loss,lambada,loss,3.725820
90,Model-1000,lambada/perplexity,lambada,perplexity,555.091018
91,Model-1000,lambada/time_since_best_accuracy,lambada,time_since_best_accuracy,0.000000
92,Model-1000,lambada/time_since_best_loss,lambada,time_since_best_loss,0.000000
93,Model-1000,mean_accuracy,mean_accuracy,mean_accuracy,0.121909
94,Model-1000,mean_loss,mean_loss,mean_loss,4.111152
95,Model-1000,piqa/accuracy/group_average,piqa,accuracy/group_average,0.521763
96,Model-1000,piqa/accuracy/seq_average,piqa,accuracy/seq_average,0.521763
97,Model-1000,piqa/accuracy/val,piqa,accuracy/val,0.521763
98,Model-1000,race/accuracy/group_average,race,accuracy/group_average,0.239219
99,Model-1000,race/accuracy/seq_average,race,accuracy/seq_average,0.237333
100,Model-1000,race/accuracy/test/high,race,accuracy/test/high,0.234706
101,Model-1000,race/accuracy/test/middle,race,accuracy/test/middle,0.243733
102,Model-1000,siqa/accuracy/dev,siqa,accuracy/dev,0.344933
103,Model-1000,siqa/accuracy/group_average,siqa,accuracy/group_average,0.344933
104,Model-1000,siqa/accuracy/seq_average,siqa,accuracy/seq_average,0.344933
105,Model-1000,val/accuracy,val,accuracy,0.241684
106,Model-1000,val/loss,val,loss,4.496483
107,Model-1000,val/perplexity,val,perplexity,89.701116
108,Model-1000,val/time_since_best_accuracy,val,time_since_best_accuracy,0.000000
109,Model-1000,val/time_since_best_loss,val,time_since_best_loss,0.000000

## Benchmark Metrics

In [4]:
benchmark_accuracy_metrics = {
    "LAMBADA": "lambada/accuracy/total",
    "BLiMP": "blimp/accuracy/group_average",
    "CBT": "cbt/accuracy/group_average",
    "HellaSwag": "hellaswag/accuracy/group_average",
    "PIQA": "piqa/accuracy/group_average",
    "ARC-Easy": "ai2arc/accuracy/group_average",
    "RACE": "race/accuracy/group_average",
    "SIQA": "siqa/accuracy/group_average",
    "CommonSenseQA": "commonsenseqa/accuracy/group_average",
}

benchmark_accuracy = pd.DataFrame(
    [
        {
            "model": model_name,
            "benchmark": label,
            "metric": metric,
            "accuracy": model_results[metric],
        }
        for model_name, model_results in loaded_results.items()
        for label, metric in benchmark_accuracy_metrics.items()
        if metric in model_results
    ]
).sort_values(["benchmark", "accuracy"], ascending=[True, False])

display(benchmark_accuracy)
benchmark_accuracy.to_csv("result-benchmark-accuracy.csv", index=False)

        model      benchmark                                metric  accuracy
5  Model-1000       ARC-Easy         ai2arc/accuracy/group_average  0.229156
1  Model-1000          BLiMP          blimp/accuracy/group_average  0.589866
2  Model-1000            CBT            cbt/accuracy/group_average  0.444664
8  Model-1000  CommonSenseQA  commonsenseqa/accuracy/group_average  0.208845
3  Model-1000      HellaSwag      hellaswag/accuracy/group_average  0.245071
0  Model-1000        LAMBADA                lambada/accuracy/total  0.002135
4  Model-1000           PIQA           piqa/accuracy/group_average  0.521763
6  Model-1000           RACE           race/accuracy/group_average  0.239219
7  Model-1000           SIQA           siqa/accuracy/group_average  0.344933

## Paper-style Table

In [5]:
def pct(model_results, metric_name):
    return model_results[metric_name] * 100

def benchmark_accuracy_pct(model_results, prefix, fallback_metric=None):
    group_average_metric = f"{prefix}/accuracy/group_average"
    if group_average_metric in model_results:
        return pct(model_results, group_average_metric)
    if fallback_metric and fallback_metric in model_results:
        return pct(model_results, fallback_metric)
    raise KeyError(f"No group_average metric found for {prefix}")

def excel_column_name(number):
    name = ""
    while number:
        number, remainder = divmod(number - 1, 26)
        name = chr(65 + remainder) + name
    return name

def write_simple_xlsx(df, path, sheet_name="Results"):
    def cell_xml(row_idx, col_idx, value):
        cell_ref = f"{excel_column_name(col_idx)}{row_idx}"
        if pd.isna(value):
            return f'<c r="{cell_ref}"/>'
        if isinstance(value, (int, float)) and not isinstance(value, bool):
            return f'<c r="{cell_ref}"><v>{value}</v></c>'
        return f'<c r="{cell_ref}" t="inlineStr"><is><t>{escape(str(value))}</t></is></c>'

    rows_xml = []
    all_rows = [list(df.columns)] + df.values.tolist()
    for row_idx, row in enumerate(all_rows, start=1):
        cells = "".join(cell_xml(row_idx, col_idx, value) for col_idx, value in enumerate(row, start=1))
        rows_xml.append(f'<row r="{row_idx}">{cells}</row>')

    sheet_xml = "".join([
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
        '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">',
        '<sheetData>',
        "".join(rows_xml),
        '</sheetData></worksheet>',
    ])
    workbook_xml = "".join([
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
        '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" ',
        'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">',
        f'<sheets><sheet name="{escape(sheet_name, quote=True)}" sheetId="1" r:id="rId1"/></sheets>',
        '</workbook>',
    ])

    with ZipFile(path, "w", ZIP_DEFLATED) as archive:
        archive.writestr("[Content_Types].xml", '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>')
        archive.writestr("_rels/.rels", '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>')
        archive.writestr("xl/workbook.xml", workbook_xml)
        archive.writestr("xl/_rels/workbook.xml.rels", '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>')
        archive.writestr("xl/worksheets/sheet1.xml", sheet_xml)

paper_rows = []
for model_name, model_results in loaded_results.items():
    paper_rows.append(
        {
            "MoE Method": model_name,
            "PPL ↓": model_results["val/perplexity"],
            "LAMBADA": pct(model_results, "lambada/accuracy/total"),
            "BLiMP": benchmark_accuracy_pct(model_results, "blimp"),
            "CBT": benchmark_accuracy_pct(model_results, "cbt"),
            "HellaSwag": benchmark_accuracy_pct(model_results, "hellaswag"),
            "PIQA": benchmark_accuracy_pct(model_results, "piqa"),
            "ARC-Easy": benchmark_accuracy_pct(model_results, "ai2arc", "ai2arc/accuracy/ARC-Easy"),
            "RACE": benchmark_accuracy_pct(model_results, "race"),
            "SIQA": benchmark_accuracy_pct(model_results, "siqa"),
            "CommonSenseQA": benchmark_accuracy_pct(model_results, "commonsenseqa"),
        }
    )

accuracy_columns = ["LAMBADA", "BLiMP", "CBT", "HellaSwag", "PIQA", "ARC-Easy", "RACE", "SIQA", "CommonSenseQA"]
paper_table = pd.DataFrame(paper_rows)
paper_table["AVG Acc ↑"] = paper_table[accuracy_columns].mean(axis=1)

rank_columns = ["PPL ↓"] + accuracy_columns
rank_table = pd.DataFrame(index=paper_table.index)
rank_table["PPL ↓"] = paper_table["PPL ↓"].rank(method="average", ascending=True)
for column in accuracy_columns:
    rank_table[column] = paper_table[column].rank(method="average", ascending=False)
paper_table["AVG Rank ↓"] = rank_table[rank_columns].mean(axis=1)
paper_table = paper_table.sort_values("AVG Rank ↓").reset_index(drop=True)

paper_table.to_csv("result-paper-table.csv", index=False)
write_simple_xlsx(paper_table, "result-paper-table.xlsx")

header_labels = ["MoE Method", "PPL ↓", "LAM<br>BADA", "BLiMP", "CBT", "Hella<br>Swag", "PIQA", "ARC-<br>Easy", "RACE", "SIQA", "Common<br>SenseQA", "AVG<br>Acc ↑", "AVG<br>Rank ↓"]
columns = list(paper_table.columns)
def format_table_value(value):
    return f"{value:.2f}" if isinstance(value, (int, float)) else str(value)
header_html = "".join(f"<th>{label}</th>" for label in header_labels)
body_html = "".join(
    "<tr>" + "".join(f"<td>{format_table_value(row[column])}</td>" for column in columns) + "</tr>"
    for _, row in paper_table.iterrows()
)
display(HTML(f"""
<style>
.paper-result-table {{
    border-collapse: collapse;
    border-top: 2px solid #111;
    border-bottom: 2px solid #111;
    font-family: 'Times New Roman', Times, serif;
    font-size: 18px;
    margin: 12px 0;
    min-width: 100%;
}}
.paper-result-table th {{
    border-bottom: 1px solid #333;
    font-size: 20px;
    font-weight: 700;
    line-height: 1.05;
    padding: 6px 12px 8px;
    text-align: center;
    white-space: nowrap;
}}
.paper-result-table td {{
    padding: 5px 12px;
    text-align: center;
}}
.paper-result-table td:first-child {{
    text-align: left;
}}
</style>
<table class="paper-result-table">
    <thead><tr>{header_html}</tr></thead>
    <tbody>{body_html}</tbody>
</table>
"""))